// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// nesage
List nesage(NumericMatrix dataMat, NumericVector library, bool updateAlpha, List modelList, int iter);
RcppExport SEXP _nesage_nesage(SEXP dataMatSEXP, SEXP librarySEXP, SEXP updateAlphaSEXP, SEXP modelListSEXP, SEXP iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dataMat(dataMatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type library(librarySEXP);
    Rcpp::traits::input_parameter< bool >::type updateAlpha(updateAlphaSEXP);
    Rcpp::traits::input_parameter< List >::type modelList(modelListSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    rcpp_result_gen = Rcpp::wrap(nesage(dataMat, library, updateAlpha, modelList, iter));
    return rcpp_result_gen;
END_RCPP
}
// estimateExpression
NumericMatrix estimateExpression(NumericMatrix cnt, NumericVector library, List modelList);
RcppExport SEXP _nesage_estimateExpression(SEXP cntSEXP, SEXP librarySEXP, SEXP modelListSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type cnt(cntSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type library(librarySEXP);
    Rcpp::traits::input_parameter< List >::type modelList(modelListSEXP);
    rcpp_result_gen = Rcpp::wrap(estimateExpression(cnt, library, modelList));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nesage_nesage", (DL_FUNC) &_nesage_nesage, 5},
    {"_nesage_estimateExpression", (DL_FUNC) &_nesage_estimateExpression, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_nesage(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
